version: '3.8'

services:
  app:
    image: ghcr.io/hadi-hani/app-name:latest
    container_name: app-name
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongouser:mongopass@mongo:27017/chatapp?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - chatnet

  mongo:
    image: mongo:7
    container_name: chat-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
    volumes:
      - mongo_data:/data/db
    networks:
      - chatnet

volumes:
  mongo_data:

networks:
  chatnet:
    driver: bridge
